"""Schema: the constrained vocabulary (enums) and Pydantic models for the
tagged-slide contract. Structural fields are produced by Pipeline A; the
semantic enrichment enums (deck-, slide-, and element-level) belong to Pipeline
B (the VLM / hand-label) and live here so the whole vocabulary is defined in one
place (init.md decision)."""

from slide_tagger.schema.enums import (
    AudienceLevel,
    AudienceLevelSlide,
    ChartPaletteConsistency,
    ChartType,
    ClientIndustry,
    ClientType,
    ConfidentialityTier,
    ContentArea,
    DeliverableFormat,
    DensityBucket,
    DominantVisualElement,
    EngagementStage,
    FontWeight,
    Geography,
    Grid,
    MasterTemplateUsage,
    MessageType,
    PlaceholderCompliance,
    Position,
    RecurringElementType,
    ReusabilityScore,
    SlidePositionRole,
    SlidePurpose,
    SlotType,
    SourceFormat,
    TextAlignment,
    TierMatchDifficulty,
    UsesActionTitles,
)
from slide_tagger.schema.models import (
    ColorPalette,
    DeckStructural,
    DeckSummary,
    Density,
    DesignSystem,
    RecurringElement,
    SlideStructural,
    TextStyle,
)
from slide_tagger.schema.tagged import (
    DeckTag,
    InferredBodyTextRule,
    InferredChartStylingRule,
    InferredColorPaletteRule,
    InferredLayoutConventionsRule,
    InferredRules,
    InferredTitleRule,
    Provenance,
    SlideTag,
    Zone,
    blank_tag,
    legend,
)

__all__ = [
    # enums — structural
    "DensityBucket",
    "FontWeight",
    "Grid",
    "Position",
    "RecurringElementType",
    "SourceFormat",
    "TextAlignment",
    # enums — deck-level enrichment
    "AudienceLevel",
    "ClientIndustry",
    "ClientType",
    "ConfidentialityTier",
    "ContentArea",
    "DeliverableFormat",
    "EngagementStage",
    "Geography",
    # enums — slide-level enrichment
    "AudienceLevelSlide",
    "ChartType",
    "DominantVisualElement",
    "MessageType",
    "PlaceholderCompliance",
    "ReusabilityScore",
    "SlidePositionRole",
    "SlidePurpose",
    "SlotType",
    "TierMatchDifficulty",
    # enums — inferred rules
    "ChartPaletteConsistency",
    "MasterTemplateUsage",
    "UsesActionTitles",
    # models — structural
    "ColorPalette",
    "DeckStructural",
    "DeckSummary",
    "Density",
    "DesignSystem",
    "RecurringElement",
    "SlideStructural",
    "TextStyle",
    # models — tagged / enrichment
    "DeckTag",
    "InferredBodyTextRule",
    "InferredChartStylingRule",
    "InferredColorPaletteRule",
    "InferredLayoutConventionsRule",
    "InferredRules",
    "InferredTitleRule",
    "Provenance",
    "SlideTag",
    "Zone",
    "blank_tag",
    "legend",
]
